
import "./globals.css";
import { Gloock} from 'next/font/google';

const gloock =   Gloock({
  subsets : [
    'latin'
  ],
  weight:'400',
  

  display:'swap'
})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${gloock.className} min-h-full flex flex-col`}>{children}</body>
    </html>
  );
}
